export const THE_BLIND_PIG = {
  slug: 'the-blind-pig',
  name: 'The Blind Pig',
  tagline: 'Chicago\'s Underground.',
  type: 'Underground Club',
  subtype: 'Nightclub / Live Music',
  accentColor: '#c026d3',
  verified: true,
  pro: true,
  city: 'Chicago',
  state: 'IL',
  neighborhood: 'Wicker Park',
  address: '1220 N Milwaukee Ave, Chicago, IL 60622',
  founded: '2011',
  memberSince: 'January 2023',

  banner: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=1600&q=80',
  logo: 'https://images.unsplash.com/photo-1571266028753-bfe6cc7f0e8e?w=400&q=80',

  description: `The Blind Pig has been the beating heart of Chicago's underground electronic scene since 2011. Carved into a former industrial warehouse in Wicker Park, the venue operates across two floors: a main room built around its legendary d&b Audiotechnik sound system, and an intimate basement stage for emerging artists and late-night extended sets.

The ethos is simple: protect the culture, respect the music, book with intention. The Blind Pig doesn't chase trends. It built the landscape.

We work with a curated network of artists, promoters, photographers, and lighting designers who understand what it means to be inside this room on a Friday night. If you're reading this on Stagefront, you already know the kind of energy we're talking about.

Residents include NOVA VEGA, SABLE, and the CRYPT0 collective. We host independent promoters, label nights, and international touring acts — but always filtered through our aesthetic. This is not a venue for everyone, and that's exactly the point.`,

  atmosphere: ['Underground', 'Intimate', 'Dark', 'Industrial', 'Curated', 'Artist-First', 'Immersive', 'No-Flash Photography'],

  stats: {
    capacity: 300,
    eventsPerMonth: 20,
    artistsHosted: 840,
    yearsActive: 13,
    rating: 4.9,
    reviewCount: 94,
    avgAttendance: 265,
    ticketsSold: 48000,
  },

  specs: {
    mainRoom: {
      capacity: 300,
      stageDimensions: '24ft × 16ft',
      ceilingHeight: '18ft',
      danceFloor: '2,400 sq ft',
    },
    basement: {
      capacity: 80,
      stageDimensions: '12ft × 10ft',
      ceilingHeight: '9ft',
      danceFloor: '600 sq ft',
    },
    sound: {
      system: 'd&b Audiotechnik V-Series',
      subwoofers: 'd&b Audiotechnik V-SUB × 4',
      monitors: 'Genelec 1032C × 4',
      mixer: 'Allen & Heath PLAYlive',
      djBooth: 'Pioneer CDJ-3000 × 4 + DJM-900NXS2',
      backline: 'Full backline available on request',
    },
    lighting: {
      system: 'Avolites Sapphire Touch Console',
      moving: 'Robe BMFL × 8, Martin MAC Viper × 6',
      static: 'Full LED wash + strobe array',
      lasers: 'Pangolin laser system',
      hazer: 'DF-50 touring hazer',
      customRigs: true,
    },
    production: {
      greenRoom: 'Private green room w/ private bathroom',
      parking: 'Loading dock available',
      wifi: 'Dedicated artist WiFi',
      catering: 'In-house rider fulfillment',
    },
  },

  genres: ['Techno', 'Industrial', 'Dark Electro', 'EBM', 'Dub Techno', 'Experimental', 'Ambient', 'Noise', 'Breakbeat', 'Acid'],

  bookingPrefs: {
    minFee: '$200',
    maxCapacity: 300,
    typicalDoorTime: '9 PM',
    typicalEndTime: '4 AM',
    advanceBooking: '4–12 weeks',
    formats: ['Headliner', 'B2B', 'Label Night', 'Residency', 'Live Act', 'AV Performance'],
    notLooking: ['Cover bands', 'Open mics', 'Corporate events', 'Wedding receptions'],
  },

  residents: [
    {
      name: 'NOVA VEGA',
      role: 'DJ / Producer',
      since: '2022',
      image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&q=80',
      slug: 'nova-vega',
    },
    {
      name: 'SABLE',
      role: 'DJ / Electronic Artist',
      since: '2023',
      image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&q=80',
      slug: 'sable',
    },
    {
      name: 'CRYPT0',
      role: 'DJ Collective',
      since: '2021',
      image: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=200&q=80',
      slug: 'crypt0',
    },
  ],

  notableBookings: [
    { name: 'Surgeon', origin: 'Birmingham, UK', year: 2024 },
    { name: 'Shackleton', origin: 'Berlin, DE', year: 2024 },
    { name: 'Headless Horseman', origin: 'Berlin, DE', year: 2023 },
    { name: 'Phase Fatale', origin: 'Berlin, DE', year: 2023 },
    { name: 'Ancient Methods', origin: 'Berlin, DE', year: 2022 },
    { name: 'SPFDJ', origin: 'Paris, FR', year: 2022 },
    { name: 'Dax J', origin: 'London, UK', year: 2023 },
    { name: 'Paula Temple', origin: 'London, UK', year: 2024 },
  ],

  upcomingEvents: [
    {
      id: 'e1',
      title: 'Subterranean Sessions Vol. 12',
      date: 'Fri, May 23',
      time: '10 PM – 4 AM',
      artists: ['NOVA VEGA', 'CRYPT0', 'LUX'],
      genres: 'Techno / Industrial',
      capacity: 300,
      ticketsSold: 247,
      ticketUrl: '#',
      price: '$15–25',
      image: 'https://images.unsplash.com/photo-1571266028753-bfe6cc7f0e8e?w=600&q=80',
      status: 'On Sale',
      featured: true,
    },
    {
      id: 'e2',
      title: 'VOID — A Night of Industrial EBM',
      date: 'Sat, May 24',
      time: '9 PM – 3 AM',
      artists: ['ADAN BOOLEAN', 'MOANA SHIFT'],
      genres: 'EBM / Industrial',
      capacity: 300,
      ticketsSold: 178,
      ticketUrl: '#',
      price: '$12',
      image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
      status: 'On Sale',
      featured: false,
    },
    {
      id: 'e3',
      title: 'Tessellate Records Label Night',
      date: 'Fri, May 30',
      time: '10 PM – 4 AM',
      artists: ['NOVA VEGA', 'SABLE', 'TBA'],
      genres: 'Techno / Dark Electro',
      capacity: 300,
      ticketsSold: 89,
      ticketUrl: '#',
      price: '$18',
      image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
      status: 'On Sale',
      featured: false,
    },
    {
      id: 'e4',
      title: 'Paula Temple — Live PA + DJ Set',
      date: 'Fri, Jun 6',
      time: '9 PM – 3 AM',
      artists: ['PAULA TEMPLE', 'NOVA VEGA (warm-up)'],
      genres: 'Industrial Techno / Noise',
      capacity: 300,
      ticketsSold: 210,
      ticketUrl: '#',
      price: '$20',
      image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
      status: 'Nearly Sold Out',
      featured: false,
    },
  ],

  openSlots: [
    { date: 'Sun, Jun 8', day: 'Sunday', available: ['Main Room', 'Basement'], type: 'Open for Proposals' },
    { date: 'Sat, Jun 14', day: 'Saturday', available: ['Basement Only'], type: 'Support Slot Open' },
    { date: 'Fri, Jun 20', day: 'Friday', available: ['Main Room'], type: 'Co-Promoter Opportunity' },
    { date: 'Sat, Jun 28', day: 'Saturday', available: ['Main Room', 'Basement'], type: 'Open for Proposals' },
    { date: 'Fri, Jul 4', day: 'Friday', available: ['Main Room'], type: 'Holiday Special' },
    { date: 'Sat, Jul 12', day: 'Saturday', available: ['Basement Only'], type: 'Emerging Artist Night' },
  ],

  pastEvents: [
    {
      month: 'April 2025',
      count: 18,
      highlights: ['Surgeon Live PA', 'Dax J', 'CRYPT0 All Night', 'Blind Pig Anniversary'],
    },
    {
      month: 'March 2025',
      count: 20,
      highlights: ['Boiler Room x Blind Pig', 'Paula Temple', 'SABLE B2B NOVA VEGA', 'Phase Fatale'],
    },
    {
      month: 'February 2025',
      count: 16,
      highlights: ['Shackleton Live', 'Headless Horseman', 'Valentine\'s Darkness'],
    },
    {
      month: 'January 2025',
      count: 15,
      highlights: ['New Year Residency w/ NOVA VEGA', 'Ancient Methods', 'EBM Special'],
    },
  ],

  photos: [
    { id: 'p1', url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600&q=80', caption: 'Main room, Friday night', credit: '@aaliyachen' },
    { id: 'p2', url: 'https://images.unsplash.com/photo-1571266028753-bfe6cc7f0e8e?w=600&q=80', caption: 'NOVA VEGA Subterranean Sessions', credit: '@shootsbycj' },
    { id: 'p3', url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80', caption: 'Dance floor, 2 AM', credit: '@aaliyachen' },
    { id: 'p4', url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80', caption: 'Lighting rig, main stage', credit: '@lightsbymax' },
    { id: 'p5', url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80', caption: 'Boiler Room recording night', credit: '@shootsbycj' },
    { id: 'p6', url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=600&q=80', caption: 'DJ booth, Pioneer CDJ-3000 setup', credit: '@aaliyachen' },
    { id: 'p7', url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=600&q=80', caption: 'Basement stage, intimate set', credit: '@photosbymike' },
    { id: 'p8', url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80', caption: 'Artist in session', credit: '@aaliyachen' },
  ],

  videos: [
    {
      id: 'v1',
      title: 'The Blind Pig — Atmosphere Film 2024',
      thumbnail: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600&q=80',
      duration: '4:22',
      views: '31K',
      platform: 'YouTube',
      featured: true,
    },
    {
      id: 'v2',
      title: 'NOVA VEGA — Subterranean Sessions Live',
      thumbnail: 'https://images.unsplash.com/photo-1571266028753-bfe6cc7f0e8e?w=600&q=80',
      duration: '1:47:22',
      views: '42K',
      platform: 'YouTube',
      featured: false,
    },
    {
      id: 'v3',
      title: 'The Sound System — d&b Audiotechnik Feature',
      thumbnail: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
      duration: '6:14',
      views: '8.2K',
      platform: 'YouTube',
      featured: false,
    },
  ],

  reviews: [
    {
      id: 'r1',
      reviewer: 'NOVA VEGA',
      reviewerType: 'Resident DJ',
      reviewerImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=80&q=80',
      rating: 5,
      date: 'April 2024',
      text: 'The Blind Pig is one of the last venues in Chicago that truly gets it. The sound system alone is worth the trip, but it\'s the entire operation — crew, vibe, crowd — that makes every night here feel like something that matters. My home.',
      verified: true,
      type: 'Residency',
    },
    {
      id: 'r2',
      reviewer: 'Paula Temple',
      reviewerType: 'International DJ',
      reviewerImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80',
      rating: 5,
      date: 'March 2024',
      text: 'Everything about this venue is right. The production team anticipated every technical need, the crowd was educated and engaged, and the sound mix in that room is exceptional. Exactly the kind of venue that makes touring worthwhile.',
      verified: true,
      type: 'Headliner',
    },
    {
      id: 'r3',
      reviewer: 'Aaliya Chen',
      reviewerType: 'Music Photographer',
      reviewerImage: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&q=80',
      rating: 5,
      date: 'February 2024',
      text: 'Shot here six times. The lighting rig is a dream — whoever designed their system understands the relationship between light and atmosphere. Crew is professional and the space lends itself to remarkable images.',
      verified: true,
      type: 'Event Photography',
    },
    {
      id: 'r4',
      reviewer: 'CRYPT0',
      reviewerType: 'DJ Collective',
      reviewerImage: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=80&q=80',
      rating: 5,
      date: 'January 2024',
      text: 'Three years as residents and the standard has never dropped. Management genuinely cares about the quality of every event. We\'ve turned down higher-paying gigs to protect our Blind Pig nights. That says everything.',
      verified: true,
      type: 'Residency',
    },
  ],

  analytics: {
    avgOccupancy: '88%',
    peakNights: 'Friday & Saturday',
    topDemographic: '24–34',
    avgTicketPrice: '$18',
    repeatVisitors: '64%',
    monthlyImpressions: '28K',
  },

  contact: {
    bookingEmail: 'booking@theblindpig.com',
    generalEmail: 'hello@theblindpig.com',
    phone: '(312) 555-0192',
    instagram: '@theblindpigchi',
    residentAdvisor: 'ra.co/clubs/theblindpig',
    website: 'theblindpig.com',
  },

  socialLinks: {
    instagram: '@theblindpigchi',
    residentAdvisor: 'ra.co/clubs/theblindpig',
    facebook: 'facebook.com/theblindpigchi',
    website: 'theblindpig.com',
    mixcloud: 'mixcloud.com/theblindpig',
  },
};

export type VenueData = typeof THE_BLIND_PIG;
